
@local = http://localhost:3333


//***********************************************
// Users
//***********************************************
###
GET {{local}}/api/v1/auth
//Content-Type: application/x-www-form-urlencoded
//Content-Type: application/json


###
POST {{local}}/api/v1/auth/register
Content-Type: application/json

{
    "name":"fafazao",
    "email":"fafazao@gmail.com",
    "password":"123456"
}


###
POST {{local}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"antimo@gmail.com",
    "password":"123456"
}



###
GET {{local}}/api/v1/auth/posts
X-Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiJmMDEzNzQ4OC1kMjQ4LTRlNjAtYWM3NS1hZTU5Nzg3MjU5OGIiLCJpYXQiOjE2NzE1NDgxMDJ9.PxCKb_rWSschFcC6X77vjLLQ6-UVa9JkZom3ZA4bQb8
